framework:
    secret: '%env(APP_SECRET)%'
    test: true
    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
        storage_factory_id: session.storage.factory.mock_file
