# User Authentication Routes
app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout
    controller: App\Controller\SecurityController::logout

app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Home Routes
app_home:
    path: /home
    controller: App\Controller\HomeController::index
    
app_home_delete:
    path: /home/delete/{id}
    controller: App\Controller\HomeController::delete

app_main:
    path: /
    controller: App\Controller\MainController::index

# Post Routes
get_all_posts:
    path: /posts
    controller: App\Controller\PostController::getAllPosts

get_post:
    path: /posts/{id}
    controller: App\Controller\PostController::getPost
    requirements:
        id: \d+

create_post:
    path: /post/new
    controller: App\Controller\PostController::createPost

update_post:
    path: /post/{id}/edit
    controller: App\Controller\PostController::updatePost
    requirements:
        id: \d+

delete_post:
    path: /post/{id}/delete
    controller: App\Controller\PostController::deletePost
    requirements:
        id: \d+

toggle_theme:
    path: /toggle-theme
    controller: App\Controller\ThemeController::toggleTheme
    methods: POST


admin_dashboard:
    path: /admin
    controller: App\Controller\AdminController::index

api_get_all_posts:
    path: /api/posts
    controller: App\Controller\PostController::apiGetAllPosts
    methods: GET

api_get_post:
    path: /api/posts/{id}
    controller: App\Controller\PostController::apiGetPost
    methods: GET

api_create_post:
    path: /api/posts
    controller: App\Controller\PostController::apiCreatePost
    methods: POST

api_update_post:
    path: /api/posts/{id}
    controller: App\Controller\PostController::apiUpdatePost
    methods: [PUT, PATCH]

api_delete_post:
    path: /api/posts/{id}
    controller: App\Controller\PostController::apiDeletePost
    methods: DELETE


api_login:
    path: /api/login
    controller: App\Controller\SecurityController::apiLogin
    methods: POST

api_logout:
    path: /api/logout
    controller: App\Controller\SecurityController::apiLogout
    methods: POST

api_register:
    path: /api/register
    controller: App\Controller\RegistrationController::apiRegister
    methods: POST

api_session_info:
    path: /api/session-info
    controller: App\Controller\SecurityController::apiSessionInfo
    methods: GET


api_add_about_me:
    path: /api/home/about-me
    controller: App\Controller\HomeController::apiAddAboutMe
    methods: POST
    
api_delete_about_me:
    path: /api/home/about-me/{id}
    controller: App\Controller\HomeController::apiDeleteAboutMe
    methods: DELETE

api_get_about_me:
    path: /api/home/about-me
    controller: App\Controller\HomeController::apiGetAboutMe
    methods: GET
    
api_update_user:
    path: /api/user/update
    controller: App\Controller\HomeController::apiUpdateUser
    methods: [PUT, PATCH]
