# config/services.yaml

parameters:

services:
    App\Command\CreateGenericServiceCommand:
        arguments:
            $filesystem: '@filesystem'
        tags: [ 'console.command' ]
    
    App\Command\CreateUserCommand:
        arguments:
            $userRepository: '@App\Repository\UserRepository'
            $passwordHasher: '@security.password_hasher'
        tags: [ 'console.command' ]
    
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Services are private by default

    App\EventListener\ExceptionListener:
        tags:
            - { name: kernel.event_listener, event: kernel.exception }
    
    App\Serializer\Normalizer\PostNormalizer:
        tags: [ 'serializer.normalizer' ]
    
    
    App\Serializer\Normalizer\KeyValueStoreNormalizer:
        tags: [ 'serializer.normalizer' ]

    App\Serializer\Normalizer\UserNormalizer:
        tags: [ 'serializer.normalizer' ]
        
        # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
